name: ci

on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_INCREMENTAL: 0

jobs:
  build:
    name: Build - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Install libusb
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libusb-1.0-0-dev

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1

      - name: Fetch
        run: cargo fetch

      - name: Format
        run: cargo fmt -- --check

      - name: Build
        run: cargo build

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Build tests
        run: cargo test --no-run

      - name: Test
        run: cargo test

      - name: Build tests (zg-co2 no-default-features)
        run: cargo test --manifest-path zg-co2/Cargo.toml --no-default-features --no-run

      - name: Test (zg-co2 no-default-features)
        run: cargo test --manifest-path zg-co2/Cargo.toml --no-default-features
