name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    name: Build - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable

    - name: Install components
      run: rustup component add --toolchain stable rustfmt clippy

    - name: Fetch
      uses: actions-rs/cargo@v1
      with:
        command: fetch

    - name: Install libusb
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install libusb-1.0-0-dev

    - name: Check
      uses: actions-rs/cargo@v1
      with:
        command: check

    - name: Format
      if: matrix.os == 'ubuntu-latest'
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        arguments: --all -- --check

    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        arguments: -- -D warnings

    - name: Test (zg-co2)
      uses: actions-rs/cargo@v1
      with:
        command: test
        arguments: --manifest-path zg-co2/Cargo.toml

    - name: Test (zg-co2 no-default-features)
      uses: actions-rs/cargo@v1
      with:
        command: test
        arguments: --manifest-path zg-co2/Cargo.toml --no-default-features

    - name: Test (co2mon)
      uses: actions-rs/cargo@v1
      with:
        command: test
        arguments: --manifest-path co2mon/Cargo.toml
